version: '3.8'

services:
  web:
    build: .
    container_name: finance-tracker
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
      - finance_data:/app/instance
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production

volumes:
  finance_data: